-- ============================================================================
-- RISKTRACE — PHASE B: DATABASE NAMESPACE SETUP
-- Target Database: RISKTRACE_DB
-- Project: Snowflake CoCo CLI Hackathon 2026 — GCC Edition
-- ============================================================================

CREATE DATABASE IF NOT EXISTS RISKTRACE_DB;

-- Create project schemas
CREATE SCHEMA IF NOT EXISTS RISKTRACE_DB.RAW;
CREATE SCHEMA IF NOT EXISTS RISKTRACE_DB.STAGING;
CREATE SCHEMA IF NOT EXISTS RISKTRACE_DB.CURATED;
CREATE SCHEMA IF NOT EXISTS RISKTRACE_DB.RISK;
CREATE SCHEMA IF NOT EXISTS RISKTRACE_DB.REGULATORY;
CREATE SCHEMA IF NOT EXISTS RISKTRACE_DB.EVIDENCE;
CREATE SCHEMA IF NOT EXISTS RISKTRACE_DB.AGENT;
CREATE SCHEMA IF NOT EXISTS RISKTRACE_DB.AUDIT;
CREATE SCHEMA IF NOT EXISTS RISKTRACE_DB.TEST;
CREATE SCHEMA IF NOT EXISTS RISKTRACE_DB.APP;

-- Create file format for raw data loading
CREATE OR REPLACE FILE FORMAT RISKTRACE_DB.RAW.JSON_FORMAT
    TYPE = 'JSON'
    STRIP_OUTER_ARRAY = TRUE;

CREATE OR REPLACE FILE FORMAT RISKTRACE_DB.RAW.CSV_FORMAT
    TYPE = 'CSV'
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    SKIP_HEADER = 1;

-- Create internal stages for synthetic data and regulatory documents
CREATE STAGE IF NOT EXISTS RISKTRACE_DB.RAW.SYNTHETIC_DATA_STAGE;
CREATE STAGE IF NOT EXISTS RISKTRACE_DB.REGULATORY.REGULATORY_DOCS_STAGE;
